---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: projector
spec:
  replicas: {{ .Values.projector.replicationFactor }}
  selector:
    matchLabels:
      app.kubernetes.io/name: projector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: projector
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
      - name: projector
        persistentVolumeClaim:
          claimName: projector
      containers:
        - name: projector
          image: "{{ .Values.projector.container.repository }}:{{ .Values.projector.container.tag }}"
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /home/projector-user
            name: projector
          env:
            - name: ORG_JETBRAINS_PROJECTOR_SERVER_HANDSHAKE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: projector
                  key: password-read-write
            - name: ORG_JETBRAINS_PROJECTOR_SERVER_RO_HANDSHAKE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: projector
                  key: password-read
          ports:
            - name: http
              containerPort: 8887
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8887
            failureThreshold: 1
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: 8887
            failureThreshold: 10
            periodSeconds: 10
